### PR TITLE
As proposed updates

### PR DESCRIPTION
**Pull request by aschuster3**
Initial discussion can be found here: https://github.com/LightshedHealth/nuggets/pull/89

I'd say a majority of people need to sign off on these seeing as it is a guide we would all follow.

### CODE REVIEW

**Comment by joedursun** [comment]
+1 from me, but I proposed most of these changes...

**Comment by luketower** [comment]
👍 I'm cool with these. Those commit messages were nice to read to see all the changes at a high level. :-)

**Comment by databyte** [comment]
Does removing the entry mean it's going to be true or do we have to include it with `enabled: true`?

**Comment by aschuster3** [comment]
@databyte Great question!  I was curious so I checked the docs [and found this helpful little tid-bit](http://rubocop.readthedocs.io/en/latest/configuration/#defaults).  TL;DR: it runs the defaults unless otherwise stated in the `.rubocop.yml`

**Comment by databyte** [comment]
You have my 👍

**Comment by phongsi** [comment]
your commit messages are excellent. i agree

**Pull request merged**
